version: "3"

networks:
  app-network:
    driver: bridge

services:
  # ---------- RabbitMQ ----------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  # ---------- SOAP service ----------
  soap_service:
    build: .
    command: >
      bash -c "
        echo 'Waiting for RabbitMQ to be ready...' &&
        sleep 20 &&
        python soap/soap_service.py
      "
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    restart: on-failure

  # ---------- worker (MDB) ----------
  worker:
    build: .
    command: >
      bash -c "
        echo 'Waiting for RabbitMQ to be ready...' &&
        sleep 25 &&
        python mdb/multithr_sinlge_queue_mdbs_routing_key.py
      "
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    restart: on-failure

  # ---------- statistics ----------
  statistics:
    build: .
    command: >
      bash -c "
        echo 'Waiting for RabbitMQ to be ready...' &&
        sleep 25 &&
        python statistics/statistics_client.py
      "
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    restart: on-failure
