version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  soap_service:
    build: .
    command: python soap_service.py
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  color_producer:
    build: .
    command: python color_producer_soap.py
    environment:
      - SOAP_WSDL_URL=http://soap_service:8000/?wsdl
    depends_on:
      - soap_service

  mdb_red:
    build: .
    command: python mdb_red.py
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - soap_service

  mdb_green:
    build: .
    command: python mdb_green.py
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - soap_service

  mdb_blue:
    build: .
    command: python mdb_blue.py
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - soap_service

  statistics_client:
    build: .
    command: python statistics_client.py
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - soap_service